import turtle as tur

def adjustment():
    scr = tur.Screen()
    scr.bgcolor("black")
    tur.pensize(2)
    tur.penup()
    tur.shape("turtle")
    tur.color("black")
    tur.pencolor("white")
    tur.goto(-200, 350)
    tur.pendown()    

def top_left_corner_shape():
    tur.begin_fill()
    tur.forward(140)
    tur.right(90)
    tur.forward(40)
    tur.right(90)
    tur.forward(100)
    tur.left(90)
    tur.forward(95)
    tur.right(90)
    tur.forward(40)
    tur.right(90)
    tur.forward(135)
    tur.color("white")
    tur.end_fill()
    
def right_long_shape():
  
    
    tur.right(90)
    tur.penup()
    tur.goto(-20, 350)
    tur.pendown()    
    tur.begin_fill()
    tur.forward(180)
    tur.right(90)
    tur.forward(200)
    tur.left(90)
    tur.forward(150)
    tur.right(90)
    tur.forward(150)
    tur.right(90)
    tur.forward(40)
    tur.right(90)
    tur.forward(110)
    tur.left(90)
    tur.forward(150)
    tur.right(90)
    tur.forward(200)
    tur.left(90)
    tur.forward(140)
    tur.right(90)
    tur.forward(40)
    tur.color("white")
    tur.end_fill()
    
def right_bottom_long_shape():
  
    
    tur.penup()
    tur.goto(310, -30)
    tur.right(180)
    tur.pendown()
    tur.begin_fill()
    tur.forward(140)
    tur.right(90)
    tur.forward(150)
    tur.left(90)
    tur.forward(150)
    tur.right(90)
    tur.forward(180)
    tur.right(90)
    tur.forward(35)
    tur.right(90)
    tur.forward(145)
    tur.left(90)
    tur.forward(150)
    tur.right(90)
    tur.forward(145)
    tur.left(90)
    tur.forward(105)
    tur.right(90)
    tur.forward(40)
    tur.color("white")
    tur.end_fill()

def bottom_right_corner_shape():
    tur.penup()
    tur.goto(-200, -320)
    tur.pendown()
    tur.begin_fill()
    tur.forward(140)
    tur.left(90)
    tur.forward(35)
    tur.left(90)
    tur.forward(105)
    tur.right(90)
    tur.forward(95)
    tur.left(90)
    tur.forward(35)
    tur.left(90)
    tur.forward(130)
    tur.color("white")
    tur.end_fill()
    
def big_r_inside_shapes():
    tur.penup()
    tur.goto(-380, 170)
    tur.pendown()
    tur.begin_fill()
    tur.right(270)
    tur.forward(405)
    tur.right(90)
    tur.forward(170)
    tur.left(25)
    tur.forward(160)
    tur.right(115)
    tur.forward(220)
    tur.right(65)
    tur.forward(80)
    tur.left(155)
    tur.forward(75)
    tur.right(90)
    tur.forward(220)
    tur.right(90)
    tur.forward(140)
    tur.right(90)
    tur.forward(40)
    tur.right(90)
    tur.forward(100)
    tur.left(90)
    tur.forward(140)
    tur.left(90)
    tur.forward(110)
    tur.right(90)
    tur.forward(60)
    tur.right(65)
    tur.forward(115)
    tur.left(65)
    tur.forward(130)
    tur.left(115)
    tur.forward(105)
    tur.right(25)
    tur.forward(140)
    tur.left(90)
    tur.forward(334)
    tur.left(90)
    tur.forward(100)
    tur.right(90)
    tur.forward(40)
    tur.right(90)
    tur.forward(137)
    tur.color("white")
    tur.end_fill()
    
    
def invoke_all_function():
    adjustment()
    top_left_corner_shape()
    right_long_shape()
    right_bottom_long_shape()
    bottom_right_corner_shape()
    big_r_inside_shapes()

invoke_all_function()
tur.hideturtle()
tur.exitonclick()
